// Shared demo data for friend activities and user avatars
export const friendActivities = [
  {
    id: 1,
    name: "Alice Green",
    emoji: "🌳",
    action: "completed daily goal",
    task: "Used public transport all week",
    timeAgo: "2h ago",
    type: "daily",
  },
  {
    id: 2,
    name: "Bob Nature",
    emoji: "🌿",
    action: "achieved milestone",
    task: "Planted 10 trees this month",
    timeAgo: "5h ago",
    type: "monthly",
  },
  {
    id: 3,
    name: "Carol Earth",
    emoji: "🌎",
    action: "completed weekly goal",
    task: "Zero waste week achieved",
    timeAgo: "1d ago",
    type: "weekly",
  },
  {
    id: 4,
    name: "David Sky",
    emoji: "🦋",
    action: "reached milestone",
    task: "Saved 1000kg CO2 emissions",
    timeAgo: "2d ago",
    type: "achievement",
  },
  {
    id: 5,
    name: "Eva Water",
    emoji: "🌊",
    action: "completed monthly goal",
    task: "Installed solar panels",
    timeAgo: "3d ago",
    type: "monthly",
  },
  {
    id: 6,
    name: "Frank Forest",
    emoji: "🌲",
    action: "joined challenge",
    task: "30-day vegetarian challenge",
    timeAgo: "3d ago",
    type: "challenge",
  },
  {
    id: 7,
    name: "Grace Garden",
    emoji: "🌺",
    action: "earned badge",
    task: "Master Composter",
    timeAgo: "4d ago",
    type: "achievement",
  },
  {
    id: 8,
    name: "Henry Hill",
    emoji: "🗻",
    action: "completed goal streak",
    task: "7-day energy saving streak",
    timeAgo: "4d ago",
    type: "streak",
  },
  {
    id: 9,
    name: "Ivy Lake",
    emoji: "🍀",
    action: "started initiative",
    task: "Community cleanup project",
    timeAgo: "5d ago",
    type: "community",
  },
  {
    id: 10,
    name: "Jack Stream",
    emoji: "💧",
    action: "reduced consumption",
    task: "50% water usage reduction",
    timeAgo: "5d ago",
    type: "achievement",
  },
  {
    id: 11,
    name: "Kelly Meadow",
    emoji: "🌸",
    action: "completed challenge",
    task: "Plastic-free month",
    timeAgo: "6d ago",
    type: "challenge",
  },
  {
    id: 12,
    name: "Leo Sun",
    emoji: "🌻",
    action: "reached milestone",
    task: "100% renewable energy",
    timeAgo: "6d ago",
    type: "milestone",
  },
  {
    id: 13,
    name: "Maya Rain",
    emoji: "🌈",
    action: "started goal",
    task: "Home composting system",
    timeAgo: "1w ago",
    type: "goal",
  },
  {
    id: 14,
    name: "Noah River",
    emoji: "🌊",
    action: "achieved goal",
    task: "Bike-to-work month",
    timeAgo: "1w ago",
    type: "achievement",
  },
  {
    id: 15,
    name: "Olivia Bloom",
    emoji: "🌼",
    action: "organized event",
    task: "Local farmers market",
    timeAgo: "1w ago",
    type: "community",
  },
]

export const getActivityFeed = (limit?: number) => {
  if (limit) {
    return friendActivities.slice(0, limit)
  }
  return friendActivities
}

export const leaderboardUsers = [
  {
    id: 1,
    name: "John Eco",
    score: 98.75,
    emoji: "🌳",
    location: { city: "New York", state: "New York", country: "USA" },
  },
  {
    id: 2,
    name: "Sarah Earth",
    score: 94.32,
    emoji: "🌎",
    location: { city: "London", state: "England", country: "UK" },
  },
  {
    id: 3,
    name: "Mike Green",
    score: 92.18,
    emoji: "🌿",
    location: { city: "Toronto", state: "Ontario", country: "Canada" },
  },
  {
    id: 4,
    name: "Lisa Sky",
    score: 91.45,
    emoji: "🦋",
    location: { city: "Sydney", state: "NSW", country: "Australia" },
  },
  {
    id: 5,
    name: "Tom River",
    score: 89.93,
    emoji: "🌊",
    location: { city: "Paris", state: "Île-de-France", country: "France" },
  },
  {
    id: 6,
    name: "Emma Forest",
    score: 88.67,
    emoji: "🌲",
    location: { city: "Berlin", state: "Berlin", country: "Germany" },
  },
  {
    id: 7,
    name: "Alex Mountain",
    score: 86.29,
    emoji: "🗻",
    location: { city: "Vancouver", state: "BC", country: "Canada" },
  },
  {
    id: 8,
    name: "Maria Sun",
    score: 85.14,
    emoji: "🌻",
    location: { city: "Madrid", state: "Madrid", country: "Spain" },
  },
  {
    id: 9,
    name: "James Ocean",
    score: 83.92,
    emoji: "🌊",
    location: { city: "Tokyo", state: "Tokyo", country: "Japan" },
  },
  {
    id: 10,
    name: "Sophie Wind",
    score: 82.45,
    emoji: "🍀",
    location: { city: "Amsterdam", state: "North Holland", country: "Netherlands" },
  },
]

